language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit

after_success:
    - if [ -n "TRAVIS_TAG" ]; then bash deploy-wordpress-plugin.sh wow-server-status-widget wow-server-status-widget.php $SVNUSER $SVNPASS; fi