language: php

php:
    - 5.3
    - 5.4

env:
    global:
        - PLUGINSLUG=wow-sever-status-widget
        - MAINFILE=wow-server-status-widget.php
    matrix:
        - WP_VERSION=latest WP_MULTISITE=0
        - WP_VERSION=latest WP_MULTISITE=1
        - WP_VERSION=3.7 WP_MULTISITE=0
        - WP_VERSION=3.7 WP_MULTISITE=1


before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
    - phpunit
    - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py

after_success:
    - python travis_after_all.py https://api.travis-ci.com
    - export $(cat .to_export_back)
    - |
        if [ "$BUILD_LEADER" = "YES" ]; then
          if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
            if ([ -n "TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]); then
              bash deploy-wordpress-plugin.sh $PLUGINSLUG $MAINFILE $TRAVIS_TAG $SVNUSER $SVNPASS;
            fi
          else
            echo "Some jobs failed"
          fi
        fi
after_failure:
    - python travis_after_all.py https://api.travis-ci.com
    - export $(cat .to_export_back)
    - |
        if [ "$BUILD_LEADER" = "YES" ]; then
          if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then
            echo "All jobs failed"
          else
            echo "Some jobs failed"
          fi
        fi
after_script:
    - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS